set(_CATKIN_CURRENT_PACKAGE "display")
set(display_MAINTAINER "ivan <ivan@todo.todo>")
set(display_DEPRECATED "")
set(display_VERSION "0.0.0")
set(display_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(display_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(display_BUILDTOOL_DEPENDS "catkin")